export const ManualData = [
    {
        "id":1,
        "sector": "Energy",
        "topic": "gas",
        "insight": "Annual Energy Outlook",
        "url": "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
        "region": "Northern America",
    },
    {
        "id":2,
        "sector": "Energy",
        "topic": "gas",
        "insight": "Annual Energy Outlook",
        "url": "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
        "region": "Northern America",
    },
    {
        "id":3,
        "sector": "Energy",
        "topic": "gas",
        "insight": "Annual Energy Outlook",
        "url": "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
        "region": "Northern America",
    },
    {
        "id":4,
        "sector": "Energy",
        "topic": "gas",
        "insight": "Annual Energy Outlook",
        "url": "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
        "region": "Northern America",
    },
    {
        "id":5,
        "sector": "Energy",
        "topic": "gas",
        "insight": "Annual Energy Outlook",
        "url": "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
        "region": "Northern America",
    },
    {
        "id":6,
        "sector": "Energy",
        "topic": "gas",
        "insight": "Annual Energy Outlook",
        "url": "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
        "region": "Northern America",
    },
    {
        "id":7,
        "sector": "Energy",
        "topic": "gas",
        "insight": "Annual Energy Outlook",
        "url": "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
        "region": "Northern America",
    },
    {
        "id":8,
        "sector": "Energy",
        "topic": "gas",
        "insight": "Annual Energy Outlook",
        "url": "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
        "region": "Northern America",
    },
    {
        "id":9,
        "sector": "Energy",
        "topic": "gas",
        "insight": "Annual Energy Outlook",
        "url": "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
        "region": "Northern America",
    },
    {
        "id":10,
        "sector": "Energy",
        "topic": "gas",
        "insight": "Annual Energy Outlook",
        "url": "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
        "region": "Northern America",
    }

]